### ISSUE TITLE
POST method

### ISSUE THREAD

**Issue by brynne8** [URenko/Access-zhwiki_demo#1]
在Win7下试了一下，确实能用。不过有些地方加载得不太好，加载好像也变慢了。POST方法也没有支持，无法登录编写维基。

https://github.com/Macronut/SNI-Mask

这个似乎更牛逼一点，不过不能在Win下用。

**Comment by URenko** [comment]
嗯，这只是个demo，试试行不行
不过不打算在这个demo基础上发展，因为
https://github.com/URenko/Access_demo
这一方法适用于更多网站，已经在写较实用的版本了。

**Comment by URenko** [comment]
新项目：
https://github.com/URenko/Accesser
